name: generators
description: A new Flutter package project.
version: 0.0.1
homepage: 'none'
publish_to: none
environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"
ddependencies:
  flutter:
    sdk: flutter
  build:
  source_gen:
  annotations:
    path: ../annotations/
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:
  annotations:
    path: ../annotations/
flutter:
dependencies:
  source_gen: ^1.3.2
